### ISSUE TITLE
Eio 1.0 progress tracking

### ISSUE THREAD

**Issue by talex5** [ocaml-multicore/eio#388]
Status of major features needed for Eio 1.0 (a tick means would be OK to ship in its current state):

Backends:
- [X] Linux io_uring.
- [x] #125 (can release as beta quality)
- [x] #456

Non-essential backends (but would be good to check that the cross-platform API works for them before 1.0 if possible):

- [x] MirageOS. Prototype (running dream-eio in a unikernel): https://github.com/TheLortex/eio-solo5
- [x] #405

Features:

- [X] Concurrency primitives: Fibers, cancellation, promises, streams and semaphores.
- [x] #382 
Lock-free waiters. Should be faster, and also needed to handle signals correctly.
- [X] Multicore support: spawn new Eio and non-Eio domains.
- [x] #387
Sharing OS resources with other domains.
- [X] Networking: Clients and servers using TCP, UDP and Unix domain sockets.
- [x] #510 
File-systems: Mostly working, but API is incomplete.
- [x] #321 
Signal handlers.
- [x] #126 
Spawning processes.
- [x] #512 
High-level domain pools API.
- [x] #553
- [x] #649

Integrations:

- [X] [Lwt_eio](https://github.com/ocaml-multicore/lwt_eio).
- [x] [Async_eio](https://github.com/talex5/async_eio): proof-of-concept works, but requires changes to async.
- [x] [Domainslib](https://github.com/ocaml-multicore/domainslib/) (#489).

Testing:

- [X] Unit tests (in `tests` directory).
- [X] Benchmarks for synchronisation primitives (in `bench` directory).
- [x] Stress tests for synchronisation primitives (in `stress` directory; currently semaphore only).
- [x] #450 
Stress tests for OS access.
- [X] Fuzz tests for parsers/serialisers (in `fuzz` directory).
- [x] Deploy at least one service using it in production.

**Comment by avsm** [comment]
I'd really like to see if we can get @patricoferris' GCD backend integrated for a 1.0 as well.

**Comment by anmonteiro** [comment]
What’s Lwt_async?

**Comment by kayceesrk** [comment]
[js_of_ocaml is ](https://github.com/ocsigen/js_of_ocaml/issues/1088) is merged now. What would js_of_ocaml support look like?

**Comment by patricoferris** [comment]
I think there are two backends that would be needed for good jsoo support, one for node and one for the browser. For a quick win in the browser, I think just taking the mock backend's scheduler might be a good place to start and adding whatever things from the standard environment make sense e.g. jsoo has a notion of a fake filesystem which could be the backend for the `fs` parts of jsoo but jsoo would probably never have a network capability (or not now https://github.com/WICG/direct-sockets)

For node, we just need to wrap the node bindings which are basically libuv. I made a start over here: https://github.com/patricoferris/eio/tree/node/lib_eio_js

**Comment by talex5** [comment]
> For a quick win in the browser, I think just taking the mock backend's scheduler might be a good place to start and adding whatever things from the standard environment make sense

Yep (actually, this is a good place to start for any backend). `Eio_main.run` is intended for Unix-type systems and it's completely OK for JS applications to use a separate `Eio_js.run` with a different set of resources.

> For node, we just need to wrap the node bindings which are basically libuv. I made a start over here: https://github.com/patricoferris/eio/tree/node/lib_eio_js

Excellent!

BTW, you might want to rebase your node backend on Eio 0.7, as there have been quite a few changes to the error handling since the commit it's based on.

**Comment by Lupus** [comment]
Is it practical to hand-roll node bindings using jsoo ffi directly nowadays? [ts2ocaml](https://github.com/ocsigen/ts2ocaml) can generate bindings out of TypeScript definitions. Bindings will use [gen_js_api](https://github.com/LexiFi/gen_js_api) to actually compile to something that will work on jsoo. For simple libraries ts2ocaml can produce compileable bindings that you can use straight away. For more complex ones like Node API it can save you 80% of work.

How fast can jsoo be with effects? So far the consensus is that it's slow and as an optimization they suggest to avoids CPS transformaton for code that does not use effects. Will Eio code (that is 100% on effects) run fast enough on jsoo to be practical to be used anywhere in production?

**Comment by patricoferris** [comment]
> Is it practical to hand-roll node bindings using jsoo ffi directly nowadays?

It's a fair point, but yes I think it is still practical as there's not _that_ many. I am also firmly in the camp of hand-rolling a bit even if you eventually automate (like hand-writing C stubs before reaching for ctypes) so you are in full control over the bindings to avoid hard to debug problems (e.g. for effects to work the calling convention _must_ use the underlying `caml_js_wrap_callback_strict` otherwise it won't be registered and I knew Brr made this update fairly quickly, I don't know if `gen_js_api` and `ts2ocaml` have ensured this (maybe they already did?)).

> How fast can jsoo be with effects?

See the latest PR https://github.com/ocsigen/js_of_ocaml/pull/1384.

As an update for this thread, there's a PR open for the browser backend. https://github.com/ocaml-multicore/eio/pull/405
